=== Inphecs/InternetworkingProject/Assignment1/web/WEB-INF/books.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.uts.edu.au/31284/wsd-books"
 xmlns="http://www.uts.edu.au/31284/wsd-books"
 elementFormDefault="qualified">

<xs:element name="books">
    <xs:complexType mixed="true">
        <xs:sequence>
         <xs:element name="book" minOccurs="0" maxOccurs="8">
          <xs:complexType>
           <xs:sequence>
               
            <xs:element name="title" type="xs:string"/>
            <xs:element name="author" type="xs:string"/>
            <xs:element name="category" type="xs:string"/>
            <xs:element name="abstract" type="xs:string"/>
            <xs:element name="isbn" type="xs:integer"/>
            <xs:element name="publishername" type="xs:string"/>
            <xs:element name="year" type="xs:integer"/>
            <xs:element name="condition" type="xs:string"/>
            <xs:element name="status" type="xs:string"/> 
                
           </xs:sequence> 
          </xs:complexType>
         </xs:element>
        </xs:sequence>    
    </xs:complexType>
</xs:element>

<xs:element name="listers">
</xs:element>

<xs:element name="reservations">
</xs:element>

</xs:schema>

=== Inphecs/InternetworkingProject/Assignment1/web/WEB-INF/books.xml
<?xml version="1.0" encoding="UTF-8"?>

<books xmlns="http://www.uts.edu.au/31284/wsd-books"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-books books.xsd">
    
    <book>
        <title>Book 1</title>
        <author>Gregory O'Connor</author>
        <category>History</category>
        <Abstract>Abstract of the first book</Abstract>
        <isbn>1234567890</isbn>
        <publishername>Name</publishername>
        <year>2016</year>
        <condition>New</condition>
        <status>Reserved</status>
    </book>
    
    <book>
        <title>Book 2</title>
        <author>Nathan Carr</author>
        <category>Technology</category>
        <Abstract>Abstract of the second book</Abstract>
        <isbn>1234567890</isbn>
        <publishername>Name</publishername>
        <year>2015</year>
        <condition>Good</condition>
        <status>Not reserved</status>
    </book>
    
    <book>
        <title>Book 3</title>
        <author>Il Sun Choi</author>
        <category>Geography</category>
        <Abstract>Abstract of the third book</Abstract>
        <isbn>1234567890</isbn>
        <publishername>Name</publishername>
        <year>2014</year>
        <condition>Fair</condition>
        <status>Reserved</status>
    </book>
    
    <book>
        <title>Book 4</title>
        <author>Chris Jeffrey</author>
        <category>Biology</category>
        <Abstract>Abstract of the fourth book</Abstract>
        <isbn>1234567890</isbn>
        <publishername>Name</publishername>
        <year>2013</year>
        <condition>Poor</condition>
        <status>Not reserved</status>
    </book>
    
    <book>
        <title>Book 5</title>
        <author>Marshmello</author>
        <category>Physics</category>
        <Abstract>Abstract of the fifth book</Abstract>
        <isbn>1234567890</isbn>
        <publishername>Name</publishername>
        <year>2012</year>
        <condition>New</condition>
        <status>Not reserved</status>
    </book>
    
    <book>
        <title>Book 6</title>
        <author>Skrillex</author>
        <category>Maths</category>
        <Abstract>Abstract of the sixth book</Abstract>
        <isbn>1234567890</isbn>
        <publishername>Name</publishername>
        <year>2011</year>
        <condition>Good</condition>
        <status>Reserved</status>
    </book>
    
    <book>
        <title>Book 7</title>
        <author>Illenium</author>
        <category>English</category>
        <Abstract>Abstract of the seventh book</Abstract>
        <isbn>1234567890</isbn>
        <publishername>Name</publishername>
        <year>2010</year>
        <condition>Fair</condition>
        <status>Not reserved</status>
    </book>
    
    <book>
        <title>Book 8</title>
        <author>San Holo</author>
        <category>Music</category>
        <Abstract>Abstract of the eighth book</Abstract>
        <isbn>1234567890</isbn>
        <publishername>Name</publishername>
        <year>2009</year>
        <condition>Poor</condition>
        <status>Reserved</status>
    </book>
    
</books>
